{
 "title": "_Loki [bitte]",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "logs", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "_Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "_Queries/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(prometheus_loki_request_duration_seconds_count{route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "_Pushes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n          rate(prometheus_loki_request_duration_seconds_count{route=~\"api_prom_push|loki_api_v1_push\"}[5m]),\n   \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "_Bad Words",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (name,level) (rate(prometheus_promtail_custom_bad_words_total[$__interval])) - \nsum by (name,level) (rate(prometheus_promtail_custom_bad_words_total[$__interval] offset 1h)))",
     "legendFormat": "{{name}}-{{level}}"
    }
   ]
  },
  {
   "title": "_Lines Per Tenant (top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(prometheus_loki_distributor_lines_received_total[5m])) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "_MBs Per Tenant (Top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(prometheus_loki_distributor_bytes_received_total[5m])) by (tenant)) / 1024 / 1024",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "_Push Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "_Distributor Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (prometheus_loki_request_duration_seconds_bucket)) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (prometheus_loki_request_duration_seconds_bucket)) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (prometheus_loki_request_duration_seconds_bucket)) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "_Distributor Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_request_duration_seconds_count{status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(prometheus_loki_request_duration_seconds_count[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "_Ingester Latency Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (prometheus_loki_request_duration_seconds_bucket{route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (prometheus_loki_request_duration_seconds_bucket{route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (prometheus_loki_request_duration_seconds_bucket{route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "_Ingester Success Rate Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_request_duration_seconds_count{status_code!~\"5[0-9]{2}\", route=\"/logproto.Pusher/Push\"}[5m])) by (route)\n/\nsum(rate(prometheus_loki_request_duration_seconds_count{route=\"/logproto.Pusher/Push\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "_Query Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.5"
    }
   ]
  },
  {
   "title": "_Querier Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "_Querier Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_request_duration_seconds_count{status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(prometheus_loki_request_duration_seconds_count[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "_Ingester Latency Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", })) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", })) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (prometheus_loki_request_duration_seconds_bucket{route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", })) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "_Ingester Success Rate Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_request_duration_seconds_count{status_code!~\"5[0-9]{2}\",route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[5m])) by (route)\n/\nsum(rate(prometheus_loki_request_duration_seconds_count{route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "_Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "_Discarded Lines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (tenant, reason) (rate(prometheus_loki_discarded_samples_total[1m])))",
     "legendFormat": "{{ tenant }} - {{ reason }}"
    }
   ]
  },
  {
   "title": "_Discarded Lines Per Interval",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "topk(10, sum by (tenant, reason) (sum_over_time(increase(prometheus_loki_discarded_samples_total[1m])[$__range:1m])))",
     "legendFormat": "{{ tenant }} - {{ reason }}"
    }
   ]
  },
  { "title": "_Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "_Active Streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum by (tenant) (prometheus_loki_ingester_memory_streams))",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "_Streams Created/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (tenant) (rate(prometheus_loki_ingester_streams_created_total[1m]) > 0))",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  { "title": "_Chunks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "_Chunks Flushed/Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_ingester_chunks_flushed_total[1m]))",
     "legendFormat": "Chunks"
    },
    {
     "expr": "sum(increase(prometheus_cortex_chunk_store_deduped_chunks_total[1m]))/sum(increase(prometheus_loki_ingester_chunks_flushed_total[1m])) < 1",
     "legendFormat": "De-Dupe Ratio"
    }
   ]
  },
  {
   "title": "_Chunk Size Bytes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_ingester_chunk_size_bytes_bucket[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "_Chunk Flush Reason",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_ingester_chunks_flushed_total{reason=\"full\"}[1m]))/sum(rate(prometheus_loki_ingester_chunks_flushed_total[1m]))",
     "legendFormat": "full"
    },
    {
     "expr": "sum(rate(prometheus_loki_ingester_chunks_flushed_total{reason=\"synced\"}[1m]))/sum(rate(prometheus_loki_ingester_chunks_flushed_total[1m]))",
     "legendFormat": "synced"
    },
    {
     "expr": "sum(rate(prometheus_loki_ingester_chunks_flushed_total{reason=\"idle\"}[1m]))/sum(rate(prometheus_loki_ingester_chunks_flushed_total[1m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(rate(prometheus_loki_ingester_chunks_flushed_total{reason=\"max_age\"}[1m]))/sum(rate(prometheus_loki_ingester_chunks_flushed_total[1m]))",
     "legendFormat": "max_age"
    }
   ]
  },
  {
   "title": "_Chunk Utilization",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by (le) (rate(prometheus_loki_ingester_chunk_utilization_bucket[1m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "_Consul", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "_Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(prometheus_cortex_consul_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(prometheus_cortex_consul_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(prometheus_cortex_consul_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  {
   "title": "_Status By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_cortex_consul_request_duration_seconds_bucket[5m])) by (operation, status_code, method)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  },
  { "title": "_BoltDB Shipper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "_Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(prometheus_loki_boltdb_shipper_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(prometheus_loki_boltdb_shipper_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(prometheus_loki_boltdb_shipper_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  {
   "title": "_Status By Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_loki_boltdb_shipper_request_duration_seconds_count[5m])) by (status_code, operation)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  },
  { "title": "_S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "_Latency By Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(prometheus_cortex_s3_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".99-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(prometheus_cortex_s3_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".9-{{operation}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(prometheus_cortex_s3_request_duration_seconds_bucket[5m])) by (operation, le))",
     "legendFormat": ".5-{{operation}}"
    }
   ]
  },
  {
   "title": "_Status By Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_cortex_s3_request_duration_seconds_count[5m])) by (status_code, operation)",
     "legendFormat": "{{status_code}}-{{operation}}"
    }
   ]
  }
 ]
}