{
 "title": "Resources saturation overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RAM used %",
   "type": "graph",
   "description": "How much RAM is in use? Relative to available system memory.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem usage %",
   "type": "graph",
   "description": "Watch filesystems filling up.",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes) > 0.1",
     "legendFormat": "{{instance}} {{mountpoint}} "
    }
   ]
  },
  {
   "title": "15 min load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Network throughput %",
   "type": "graph",
   "description": "Shows most saturated network link for every node.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (((rate(node_network_transmit_bytes_total{device!=\"lo\"}[5m]) + rate(node_network_receive_bytes_total{device!=\"lo\"}[5m]))) / node_network_speed_bytes > 0)"
    }
   ]
  },
  {
   "title": "Network latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "\n" }
   ]
  }
 ]
}